# PUT YOUR GITHUB ACTION WORKFLOW HERE

name: GitHub Action

on:
  workflow_dispatch:
  # PUT YOUR TRIGGER HERE 

jobs:
  job-name: # CALL THE JOB SOMETHING
    runs-on: ubuntu-latest  
    
    steps:
      - uses: actions/checkout@v4

      - name: Run a thing 
        run: echo "hello world"
      # PUT AN ACTUAL STEP HERE
