# Candace Savonen Oct 2025

name: Docker Test

on:
  push:
    branches:
      - 'main'
    paths: [ docker/Dockerfile ]
    
jobs:
  docker-test:
    runs-on: ubuntu-latest

    steps:
      # Need to checkout the files from this
      - uses: actions/checkout@v4

      # Attempt to build the docker image
      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          push: false
          # What directory should this be building from?
          context: docker
          # Where's the Dockerfile to build this image from?
          file: docker/Dockerfile

