# PUT YOUR GITHUB ACTION WORKFLOW HERE

name: GitHub Action

on:
  pull_request:

jobs:
  job-name: # CALL THE JOB SOMETHING
    runs-on: ubuntu-latest  
    
    steps:

      - name: actions/checkout@v4
        
